{
  "headers": {
    "X-CLIENT-ID": "sdfsf",
    "X-CLIENT-SECRET": "sdfds",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.28.4",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "cbb249c2-f074-4829-b4df-07026910f8cd",
    "host": "localhost:8082",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "236652"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "https",
  "queryParams": {},
  "requestUri": "/api/insertData",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/insertData",
  "listenerPath": "/api/*",
  "relativePath": "/api/insertData",
  "localAddress": "/127.0.0.1:8082",
  "uriParams": {},
  "rawRequestUri": "/api/insertData",
  "rawRequestPath": "/api/insertData",
  "remoteAddress": "/127.0.0.1:62832",
  "requestPath": "/api/insertData"
}